version: '3.8'

services:
  ollama:
    volumes:
      - /home/ollama:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    image: ollama/ollama:latest
    hostname: ollama
    networks:
        - mynetwork
    devices:
      - /dev/dri:/dev/dri

  ollama-webui:
    ports:
      - "3000:8080"
    volumes:
      - /home/ollama-webui:/app/backend/data
    container_name: ollama-webui
    restart: always
    image: ghcr.io/open-webui/open-webui:main
    hostname: ollama-webui
    networks:
        - mynetwork
    environment:
        - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  app:
    ports:
      - "8080:8080"
    container_name: ollama-hello-there
    restart: always
    image: ollama-hello-there
    hostname: app
    networks:
      - mynetwork
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

networks:
  mynetwork:
